services:
  cicd:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tmp:/tmp
      - logs:/logs
      - secrets:/secrets
    networks:
      - cicd-caddy
    labels:
      caddy: cicd.applyinnovations.au
      caddy.reverse_proxy: "{{upstreams 80}}"

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - cicd-caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    deploy:
      labels: # Global options
        caddy.email: hello@applyinnovations.com.au
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: "0.1"
          memory: 200M

networks:
  cicd-caddy:
    name: cicd-caddy
    driver: bridge 

volumes:
  caddy_data:
  logs:
  tmp:
  secrets:
