services:
  cicd:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/cicd-cache:/tmp/cicd-cache
    networks:
      - proxy

  proxy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
