services:
  cicd:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - cicd_tmp:/tmp
      - cicd_logs:/logs
    networks:
      - caddy
    labels:
      caddy: cicd.applyinnovations.au
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "internal"

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    deploy:
      labels:
        caddy.email: hello@applyinnovations.com.au
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy: unless-stopped
      resources:
        reservations:
          cpus: "0.1"
          memory: 200M

networks:
  caddy:
    name: caddy
    driver: overlay

volumes:
  caddy_data:
  cicd_logs:
  cicd_tmp:
