services:
  cicd:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

  proxy:
    image: caddy:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  proxy:
    driver: bridge
