services:
  cicd:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/cicd-cache:/tmp/cicd-cache
    networks:
      - proxy

networks:
  proxy:
    name: cicd-proxy
    external: true
