tracing:
  serviceName: traefik

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    asDefault: true

certificatesResolvers:
  applyinnovations:
    acme:
      email: hello@applyinnovations.com.au
      storage: /certificates/applyinnovations-acme.json
      httpChallenge:
        entryPoint: web
api:
  insecure: true
  dashboard: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-proxy
